# Generated by Django 4.1.3 on 2022-11-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField(default='picture')),
                ('description', models.TextField(default='this is a picture')),
                ('location', models.TextField(default='here')),
            ],
        ),
    ]
