# Generated by Django 4.1.3 on 2022-11-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridge_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.TextField(default='this is true'),
        ),
    ]
