# Generated by Django 4.1.3 on 2022-11-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='duedate',
            new_name='date',
        ),
    ]
